# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OC知识点' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OC知识点
  pod 'PureLayout', '~> 3.0.2'
  pod 'AFNetworking', '~> 3.2.1'

  target 'OC知识点Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OC知识点UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
